name: shell-script-run
on: workflow_dispatch
jobs:
    shell_script_run_job:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
              name: source code check out
            - run: git update-index --chmod=+x ./shell_script.sh  
            - run: bash shell_script.sh



