name: shell-script-run
on: workflow_dispatch
jobs:
    shell_script_run_job:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
              name: source code check out
            - run: ls ${GITHUB_WORKSPACE}
              name: Print GITHUB_WORKSPACE
            #- run: git update-index --chmod=+x ./shell_script.sh  
            - run: echo hostname
              name: shell script run



